baseURL = "http://example.org/"
languageCode = "fr-FR"
title = "Formao"
theme = "zeo"

enableEmoji = true

# Pour la fonctionnalité de recherche

#[outputs]
# home = [ "HTML", "RSS", "JSON"]

[blackfriday]
hrefTargetBlank = true

